In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


#   EJERCICIO 1 #

In [5]:
import numpy as np

In [9]:
cantidades = np.array ([
    [6, 5, 3, 1],
 [3, 6, 2, 2],
 [3, 4, 3, 1]])

precios = np.array([
    [1.5, 1], 
    [2, 2.5], 
    [5, 4.5], 
    [16, 17]])

gasto = cantidades @ precios
print("matriz de gasto( filas= personas, columnas=tiendas):")
print(gasto)

matriz de gasto( filas= personas, columnas=tiendas):
[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]


In [3]:
Solucion = "Teniendo en cuenta los resultados, Rafa irá al Starbucks, Nacho irá a Manolo Bakes y a Clara le es indiferente "
print(Solucion)

Teniendo en cuenta los resultados, Rafa irá al Starbucks, Nacho irá a Manolo Bakes y a Clara le es indiferente 


# EJERCICIO 2 #

In [5]:
import numpy as np

In [8]:
generos = ["accion", "aventura", "animacion","comedia","romance"]
peliculas = {"toy story":[0,1,1,1,0], "jumanji":[0,1,0,0,0], "mortal_kombat":[1,1,0,0,0], "pocahontas":[0,0,1,0,1]}

matriz = np.array(list(peliculas.values()))

print(" Matriz de películas:\n", matriz)
print("\nDimensión:", matriz.ndim)
print("Shape:", matriz.shape)
print("Tamaño total:", matriz.size)
print("Tipo:", type(matriz))

 Matriz de películas:
 [[0 1 1 1 0]
 [0 1 0 0 0]
 [1 1 0 0 0]
 [0 0 1 0 1]]

Dimensión: 2
Shape: (4, 5)
Tamaño total: 20
Tipo: <class 'numpy.ndarray'>


In [9]:
def similitud_coseno(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [11]:
nombres = list(peliculas.keys())

print("\nSimilitud entre películas:\n")
for i in range(len(nombres)):
    for j in range(i+1, len(nombres)):
        sim = similitud_coseno(matriz[i], matriz[j])
        print(f"{nombres[i]} , {nombres[j]}: {sim:.2f}")


Similitud entre películas:

toy story , jumanji: 0.58
toy story , mortal_kombat: 0.41
toy story , pocahontas: 0.41
jumanji , mortal_kombat: 0.71
jumanji , pocahontas: 0.00
mortal_kombat , pocahontas: 0.00


In [12]:
wall_e = np.array([1, 1, 0, 1, 0])

print("\n Similitud de Wall-E con las demás:\n")
for i, nombre in enumerate(nombres):
    sim = similitud_coseno(wall_e, matriz[i])
    print(f"Wall-E ↔ {nombre}: {sim:.2f}")


 Similitud de Wall-E con las demás:

Wall-E ↔ toy story: 0.67
Wall-E ↔ jumanji: 0.58
Wall-E ↔ mortal_kombat: 0.82
Wall-E ↔ pocahontas: 0.00
